#!/bin/bash
# Build script, call with option -d before each commit
# Options:
# -b builds for release
# -d generates documentation

while [ "$1" != "" ]; do
  case $1 in 
    -r) 
      
      #delete release folder
      rm -rI release

      #compile typescript and sass
      tsc
      sass Client/main.scss Client/main.css
      
      #create release folder
      mkdir release
      mkdir release/Client
      mkdir release/Games
      mkdir release/Games/Classic
      mkdir release/Games/OneDay

      #copy over all necessary files
      cp app.js release
      cp core.js release
      cp LICENSE release
      cp README.md release
      cp package-lock.json release
      cp package.json release
      cp -r node_modules release
      cp -r views release
      
      #minify javascript and css on clientside
      uglifyjs --compress --comments '/license/' -- Client/client.js > release/Client/client.js
      cleancss -o release/Client/main.css Client/main.css

      cp Games/OneDay/oneDay.js release/Games/OneDay
      cp Games/Classic/classic.js release/Games/Classic

      ;;

    -d)

      #generate documentation
      typedoc --out docs --excludeExternals --externalPattern "**/node_modules/**" --ignoreCompilerErrors ../OpenWerewolf --target es6 --theme default --readme none

      #add .nojekyll to docs folder so that github pages accepts urls with underscores
      touch docs/.nojekyll

      ;;
    
    *)
      
      ;;
	
  esac
  shift
done
