#!/bin/bash
# Build script, call before each commit

#compile typescript
tsc

#generate documentation
typedoc --out docs ../OpenWerewolf --target es6 --theme default --readme none

#add .nojekyll to docs folder so that github pages accepts urls with underscores
touch docs/.nojekyll

#create release folder
mkdir release
cp *.js release
mkdir release/Games
mkdir release/Games/OneDay
mkdir release/Games/Classic
cp Games/*.js release/Games
cp Games/OneDay/*.js release/Games/OneDay
cp Games/Classic/*.js release/Games/Classic
cp -r node_modules release
cp -r Client release
cp client.html release

#zip release
zip release.zip release/*

#delete release folder
rm -rI release